/* CVS $Id: $ */
package net.maxgigapop.www.rains.ontmodel; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /Users/xyang/Work/RAINS/nml-mrs-model/source/rdf-model-examples/src/main/resources/mrs-spa.owl 
 * @author Auto-generated by schemagen on 24 Apr 2015 14:31 
 */
public class Spa {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://schemas.ogf.org/mrs/2015/02/spa#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property connectType = m_model.createProperty( "http://schemas.ogf.org/mrs/2015/02/spa#connectType" );
    
    public static final Property connectWith = m_model.createProperty( "http://schemas.ogf.org/mrs/2015/02/spa#connectWith" );
    
    public static final Property dependOn = m_model.createProperty( "http://schemas.ogf.org/mrs/2015/02/spa#dependOn" );
    
    public static final Property exportTo = m_model.createProperty( "http://schemas.ogf.org/mrs/2015/02/spa#exportTo" );
    
    public static final Property importFrom = m_model.createProperty( "http://schemas.ogf.org/mrs/2015/02/spa#importFrom" );
    
    public static final Property matchAttribute = m_model.createProperty( "http://schemas.ogf.org/mrs/2015/02/spa#matchAttribute" );
    
    public static final Property matchCondition = m_model.createProperty( "http://schemas.ogf.org/mrs/2015/02/spa#matchCondition" );
    
    public static final Property operator = m_model.createProperty( "http://schemas.ogf.org/mrs/2015/02/spa#operator" );
    
    public static final Property stitchType = m_model.createProperty( "http://schemas.ogf.org/mrs/2015/02/spa#stitchType" );
    
    public static final Property stitchWith = m_model.createProperty( "http://schemas.ogf.org/mrs/2015/02/spa#stitchWith" );
    
    public static final Property type = m_model.createProperty( "http://schemas.ogf.org/mrs/2015/02/spa#type" );
    
    public static final Property value = m_model.createProperty( "http://schemas.ogf.org/mrs/2015/02/spa#value" );
    
    public static final Resource Abstraction = m_model.createResource( "http://schemas.ogf.org/mrs/2015/02/spa#Abstraction" );
    
    public static final Resource Condition = m_model.createResource( "http://schemas.ogf.org/mrs/2015/02/spa#Condition" );
    
    public static final Resource Connection = m_model.createResource( "http://schemas.ogf.org/mrs/2015/02/spa#Connection" );
    
    public static final Resource Placement = m_model.createResource( "http://schemas.ogf.org/mrs/2015/02/spa#Placement" );
    
    public static final Resource PolicyAction = m_model.createResource( "http://schemas.ogf.org/mrs/2015/02/spa#PolicyAction" );
    
    public static final Resource PolicyData = m_model.createResource( "http://schemas.ogf.org/mrs/2015/02/spa#PolicyData" );
    
    public static final Resource Stitching = m_model.createResource( "http://schemas.ogf.org/mrs/2015/02/spa#Stitching" );
    
}
