/* CVS $Id: $ */
package net.maxgigapop.www.rains.ontmodel; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from /Users/xyang/Work/RAINS/nml-mrs-model/source/rdf-model-examples/src/main/resources/mrs-uspm.owl 
 * @author Auto-generated by schemagen on 24 Apr 2015 14:31 
 */
public class Uspm {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://schemas.ogf.org/mrs/2014/01/uspm#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property assertion = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#assertion" );
    
    public static final Property createdAt = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#createdAt" );
    
    public static final Property createdBy = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#createdBy" );
    
    public static final Property creates = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#creates" );
    
    public static final Property delegates = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#delegates" );
    
    public static final Property expiresAt = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#expiresAt" );
    
    public static final Property hasDelegation = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#hasDelegation" );
    
    public static final Property hasPolicy = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#hasPolicy" );
    
    public static final Property hasSession = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#hasSession" );
    
    public static final Property hasView = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#hasView" );
    
    public static final Property ownedBy = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#ownedBy" );
    
    public static final Property owns = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#owns" );
    
    public static final Property privilege = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#privilege" );
    
    public static final Property recursive = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#recursive" );
    
    public static final Property scope = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#scope" );
    
    public static final Property sharedBy = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#sharedBy" );
    
    public static final Property shares = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#shares" );
    
    public static final Property startsAt = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#startsAt" );
    
    public static final Property usedBy = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#usedBy" );
    
    public static final Property uses = m_model.createProperty( "http://schemas.ogf.org/mrs/2014/01/uspm#uses" );
    
    public static final Resource Agent = m_model.createResource( "http://schemas.ogf.org/mrs/2014/01/uspm#Agent" );
    
    public static final Resource Delegation = m_model.createResource( "http://schemas.ogf.org/mrs/2014/01/uspm#Delegation" );
    
    public static final Resource Policy = m_model.createResource( "http://schemas.ogf.org/mrs/2014/01/uspm#Policy" );
    
    public static final Resource Session = m_model.createResource( "http://schemas.ogf.org/mrs/2014/01/uspm#Session" );
    
    public static final Resource User = m_model.createResource( "http://schemas.ogf.org/mrs/2014/01/uspm#User" );
    
    public static final Resource View = m_model.createResource( "http://schemas.ogf.org/mrs/2014/01/uspm#View" );
    
}
